trigger:
- main
- plswork

pool:
  vmImage: ubuntu-latest

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:

# Clean and compile
- task: Maven@4
  displayName: 'Maven clean and compile'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    jdkArchitectureOption: 'x64'
    goals: 'clean compile'
    options: '-e'

# Run integration tests
- task: Maven@4
  displayName: 'Run Integration Tests'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test'
    options: '-e -Dspring.profiles.active=test'
  continueOnError: true

# Package the application
- task: Maven@4
  displayName: 'Maven package'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    jdkArchitectureOption: 'x64'
    goals: 'package'
    options: '-e -DskipTests'

# Publish test results
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Integration Tests'
    failTaskOnFailedTests: true
    mergeTestResults: true
  condition: always()

# Copy JAR to staging directory
- task: CopyFiles@2
  displayName: 'Copy JAR to staging'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  condition: succeeded()

# Publish artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  condition: succeeded()

# Deploy to Azure Web App
- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'YOUR_SERVICE_CONNECTION_NAME'
    appType: 'webAppLinux'
    appName: 'YOUR_WEB_APP_NAME'
    package: '$(Build.ArtifactStagingDirectory)/*.jar'
    runtimeStack: 'JAVA|21-java21'
    startUpCommand: 'java -jar /home/site/wwwroot/*.jar'
  condition: succeeded()